// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const bookOpenAltLightPng = 'assets/images/Book_open_alt_light.png';
  static const bottom1Png = 'assets/images/bottom1.png';
  static const bottom2Png = 'assets/images/bottom2.png';
  static const bottom3Png = 'assets/images/bottom3.png';
  static const bottom4Png = 'assets/images/bottom4.png';
  static const frame2Png = 'assets/images/Frame2.png';
  static const frame3Png = 'assets/images/Frame3.png';
  static const frame4Png = 'assets/images/Frame4.png';
  static const frame5Png = 'assets/images/Frame5.png';
  static const frame6Png = 'assets/images/Frame6.png';
  static const frame7Png = 'assets/images/Frame7.png';
  static const frame8Png = 'assets/images/Frame8.png';
  static const framePng = 'assets/images/Frame.png';
  static const group1Png = 'assets/images/Group1.png';
  static const group2Png = 'assets/images/Group2.png';
  static const group3Png = 'assets/images/Group3.png';
  static const group4Png = 'assets/images/Group4.png';
  static const group5Png = 'assets/images/Group5.png';
  static const groupPng = 'assets/images/Group.png';
  static const logo1Png = 'assets/images/logo1.png';
  static const logo2Png = 'assets/images/logo2.png';
  static const rectangle1Png = 'assets/images/Rectangle1.png';
  static const rectangle2Png = 'assets/images/Rectangle2.png';
  static const rectangle3Png = 'assets/images/Rectangle3.png';
  static const rectangle4Png = 'assets/images/Rectangle4.png';
  static const rectanglePng = 'assets/images/Rectangle.png';
  static const vector1Png = 'assets/images/Vector1.png';
  static const vectorPng = 'assets/images/Vector.png';
}

class AssetsSvgs {

}

